# Generated by Django 5.1.4 on 2024-12-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featured_text',
            field=models.TextField(blank=True, help_text='A featured text or excerpt from the blog, with rich text support.', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=models.TextField(blank=True, help_text='The main content of the blog post, with rich text support.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalblog',
            name='featured_text',
            field=models.TextField(blank=True, help_text='A featured text or excerpt from the blog, with rich text support.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalblog',
            name='text',
            field=models.TextField(blank=True, help_text='The main content of the blog post, with rich text support.', null=True),
        ),
    ]
